using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

// Compiles docs/DEMO.md from the Playwright demo-capture results (docs/demo-captures/results.json)
// + screenshots. Run from the repo root:  dotnet run --project tools/DemoDocBuilder
// Optional arg: repo root (defaults to the current directory).

var repo = args.Length > 0 ? args[0] : Directory.GetCurrentDirectory();
var capturesDir = Path.Combine(repo, "docs", "demo-captures");
var resultsPath = Path.Combine(capturesDir, "results.json");
var outPath = Path.Combine(repo, "docs", "DEMO.md");

if (!File.Exists(resultsPath))
{
    Console.Error.WriteLine($"results.json not found at {resultsPath}");
    return 1;
}

var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
var rows = JsonSerializer.Deserialize<List<Record>>(File.ReadAllText(resultsPath), opts) ?? [];

// Dedupe per (model, kind, scenario), PREFERRING a successful capture (a scenario captured OK in any
// pass counts as OK even if a later retry timed out); among OK records the last wins.
var deduped = new Dictionary<string, Record>();
foreach (var r in rows)
{
    var key = $"{r.Model}|{r.Kind}|{r.Scenario}";
    if (!deduped.TryGetValue(key, out var existing) || r.Ok || !existing.Ok)
        deduped[key] = r;
}
var records = deduped.Values.ToList();

// Group by model, preserving first-seen order.
var byModel = new List<(string Model, List<Record> Recs)>();
var index = new Dictionary<string, int>();
foreach (var r in records)
{
    if (!index.TryGetValue(r.Model, out var i))
    {
        index[r.Model] = byModel.Count;
        byModel.Add((r.Model, []));
        i = byModel.Count - 1;
    }
    byModel[i].Recs.Add(r);
}

var total = records.Count;
var ok = records.Count(r => r.Ok);
var bad = records.Where(r => !r.Ok).ToList();

var sb = new StringBuilder();
sb.AppendLine("# Foundry Local — Per-Model Demo Walkthrough");
sb.AppendLine();
sb.AppendLine("Auto-generated by `tools/DemoDocBuilder` from `tests/demo-capture.spec.ts`: every demo scenario");
sb.AppendLine("for every model, driven through the React SPA via Playwright (select model → click scenario chip →");
sb.AppendLine("run → capture the model's output and a screenshot).");
sb.AppendLine();
sb.AppendLine($"**Coverage:** {byModel.Count} models · {total} scenario runs · {ok} produced output · {bad.Count} empty/error.");
sb.AppendLine();
sb.AppendLine("## Models");
sb.AppendLine();
foreach (var (model, _) in byModel)
    sb.AppendLine($"- [{model}](#{Anchor(model)})");
sb.AppendLine();

foreach (var (model, recs) in byModel)
{
    sb.AppendLine();
    sb.AppendLine("---");
    sb.AppendLine();
    sb.AppendLine($"## {model}");
    sb.AppendLine();
    var caps = KindOrder.Where(k => recs.Any(r => r.Kind == k)).Select(k => KindTitle[k]);
    sb.AppendLine($"_Capabilities exercised: {string.Join(", ", caps)}_");
    sb.AppendLine();

    foreach (var kind in KindOrder.Where(k => recs.Any(r => r.Kind == k)))
    {
        sb.AppendLine($"### {KindTitle[kind]}");
        sb.AppendLine();
        foreach (var r in recs.Where(r => r.Kind == kind))
        {
            var label = Labels.TryGetValue(kind, out var m) && m.TryGetValue(r.Scenario, out var l) ? l : r.Scenario;
            var status = r.Ok ? "✅" : "⚠️";
            sb.AppendLine($"#### {status} {label}");
            sb.AppendLine();
            if (!string.IsNullOrWhiteSpace(r.Prompt))
            {
                sb.AppendLine($"**Prompt:** {Clip(r.Prompt, 400)}");
                sb.AppendLine();
            }
            if (r.Ok)
                sb.AppendLine($"**Output:** {Clip(r.Output, 700)}");
            else
                sb.AppendLine($"**Result:** _empty/error_ — {Clip(string.IsNullOrEmpty(r.Error) ? r.Output : r.Error, 300)}");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(r.Screenshot) && File.Exists(Path.Combine(capturesDir, r.Screenshot)))
            {
                sb.AppendLine($"![{model} {kind} {r.Scenario}](./demo-captures/{r.Screenshot})");
                sb.AppendLine();
            }
        }
    }
}

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString());
Console.WriteLine($"Wrote {outPath}: {byModel.Count} models, {total} runs, {ok} ok, {bad.Count} empty/error");
foreach (var r in bad)
    Console.WriteLine($"  empty/error: {r.Model} {r.Kind}/{r.Scenario} — {Clip(string.IsNullOrEmpty(r.Error) ? r.Output : r.Error, 80)}");
return 0;

static string Clip(string? s, int n)
{
    s = (s ?? string.Empty).Trim().Replace("\r", "");
    return s.Length > n ? s[..n] + "…" : s;
}

static string Anchor(string model) => model.Replace(".", "").Replace("_", "-");

sealed record Record
{
    public string Model { get; init; } = "";
    public string Kind { get; init; } = "";
    public string Scenario { get; init; } = "";
    public bool Ok { get; init; }
    public string? Output { get; init; }
    public string? Error { get; init; }
    public string? Prompt { get; init; }
    public string? Screenshot { get; init; }
}

partial class Program
{
    static readonly string[] KindOrder = ["text", "code", "reasoning", "vision", "tools", "audio"];
    static readonly Dictionary<string, string> KindTitle = new()
    {
        ["text"] = "Text", ["code"] = "Code", ["reasoning"] = "Reasoning",
        ["vision"] = "Vision", ["tools"] = "Tools", ["audio"] = "Speech-to-text",
    };
    static readonly Dictionary<string, Dictionary<string, string>> Labels = new()
    {
        ["text"] = new() { ["qa"] = "Q&A", ["summarize"] = "Summarize", ["translate"] = "Translate", ["sentiment"] = "Classify", ["extract"] = "Extract JSON", ["rewrite"] = "Rewrite", ["conversation"] = "Multi-turn chat" },
        ["code"] = new() { ["generate"] = "Generate", ["explain"] = "Explain", ["bug"] = "Find the bug", ["tests"] = "Write tests", ["translate"] = "Port language", ["iterate"] = "Iterative coding" },
        ["reasoning"] = new() { ["math"] = "Word problem", ["logic"] = "Logic puzzle", ["plan"] = "Plan", ["compare"] = "Compare", ["estimate"] = "Estimate", ["followup"] = "Follow-up reasoning" },
        ["vision"] = new() { ["describe"] = "Describe", ["ocr"] = "Read text (OCR)", ["color"] = "Shape & color", ["count"] = "Count", ["sceneqa"] = "Visual Q&A", ["upload"] = "Upload your own" },
        ["tools"] = new() { ["weather"] = "Weather", ["calculate"] = "Calculator", ["both"] = "Two tools", ["forced"] = "Forced tool", ["multiturn"] = "Full tool loop" },
        ["audio"] = new() { ["pangram"] = "Pangram clip", ["numbers"] = "Numbers clip", ["pangram-en"] = "Pangram (lang=en)", ["numbers-en"] = "Numbers (lang=en)", ["upload"] = "Upload" },
    };
}
