using System.Diagnostics;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

// Measures, for every model in the catalog, how long ONE demo run takes against the live server
// (under the current MaxResponseTokens), and emits per-model "typical seconds" data files consumed
// by the React SPA and the Blazor client to label demo buttons with an expected run time.
//
// Usage: dotnet run --project tools/DemoTimingProbe -- [<serverBase>] [<repoRoot>]
//   serverBase default: http://localhost:5537
//   repoRoot   default: current directory

var serverBase = (args.Length > 0 ? args[0] : "http://localhost:5537").TrimEnd('/');
var repoRoot = args.Length > 1 ? args[1] : Directory.GetCurrentDirectory();

var http = new HttpClient { Timeout = TimeSpan.FromMinutes(15) };

// Catalog + per-model capability flags.
var modelsJson = await http.GetStringAsync($"{serverBase}/api/models");
var available = JsonNode.Parse(modelsJson)!["available"]!.AsArray();

// Assets for vision / audio probes.
var imgPath = Path.Combine(repoRoot, "frontend", "tests", "assets", "green-circle.png");
var wavPath = Path.Combine(repoRoot, "frontend", "public", "sample-pangram.wav");
string? imageDataUri = File.Exists(imgPath)
    ? "data:image/png;base64," + Convert.ToBase64String(await File.ReadAllBytesAsync(imgPath))
    : null;

const string TextPrompt = "In a short paragraph, explain why running language models locally is useful.";

var results = new List<(string Id, int Seconds, string Kind)>();

foreach (var node in available)
{
    var id = node!["id"]!.GetValue<string>();
    bool Cap(string c) => node[c]?.GetValue<bool>() ?? false;
    var kind = Cap("audio") ? "audio" : Cap("vision") ? "vision" : "chat";

    var sw = Stopwatch.StartNew();
    try
    {
        if (kind == "audio")
        {
            using var form = new MultipartFormDataContent();
            var bytes = await File.ReadAllBytesAsync(wavPath);
            var fileContent = new ByteArrayContent(bytes);
            fileContent.Headers.ContentType = new MediaTypeHeaderValue("audio/wav");
            form.Add(fileContent, "file", "sample-pangram.wav");
            form.Add(new StringContent(id), "model");
            using var resp = await http.PostAsync($"{serverBase}/v1/audio/transcriptions", form);
            await resp.Content.ReadAsStringAsync();
        }
        else
        {
            JsonNode content = kind == "vision" && imageDataUri is not null
                ? new JsonArray(
                    new JsonObject { ["type"] = "text", ["text"] = "Describe this image briefly." },
                    new JsonObject { ["type"] = "image_url", ["image_url"] = new JsonObject { ["url"] = imageDataUri } })
                : TextPrompt;

            var body = new JsonObject
            {
                ["model"] = id,
                ["messages"] = new JsonArray(new JsonObject { ["role"] = "user", ["content"] = content }),
            };
            using var resp = await http.PostAsync($"{serverBase}/v1/chat/completions",
                new StringContent(body.ToJsonString(), Encoding.UTF8, "application/json"));
            await resp.Content.ReadAsStringAsync();
        }
        sw.Stop();
        var secs = (int)Math.Max(1, Math.Round(sw.Elapsed.TotalSeconds));
        results.Add((id, secs, kind));
        Console.WriteLine($"{id,-34} {kind,-7} {secs,4}s");
    }
    catch (Exception ex)
    {
        sw.Stop();
        Console.WriteLine($"{id,-34} {kind,-7}  ERR {ex.Message.Split('\n')[0]}");
        // record 0 → treated as "unknown" by the UI (no label)
        results.Add((id, 0, kind));
    }
}

// ── Emit the React data file ──
var ts = new StringBuilder();
ts.AppendLine("// AUTO-GENERATED by tools/DemoTimingProbe — do not edit by hand.");
ts.AppendLine("// Typical seconds for ONE run of a demo, per model, measured live against the server");
ts.AppendLine("// at the configured MaxResponseTokens. Multiply by a scenario's request count");
ts.AppendLine("// (multi-turn = 3 turns, full tool loop = 2) for multi-step demos. 0 = unknown.");
ts.AppendLine("export const demoTimings: Record<string, number> = {");
foreach (var r in results) ts.AppendLine($"  \"{r.Id}\": {r.Seconds},");
ts.AppendLine("};");
var tsPath = Path.Combine(repoRoot, "frontend", "src", "demoTimings.ts");
await File.WriteAllTextAsync(tsPath, ts.ToString());
Console.WriteLine($"\nWrote {tsPath}");

// ── Emit the Blazor data file ──
var cs = new StringBuilder();
cs.AppendLine("// AUTO-GENERATED by tools/DemoTimingProbe — do not edit by hand.");
cs.AppendLine("namespace FoundryLocalLlmServer.BlazorClient;");
cs.AppendLine();
cs.AppendLine("/// <summary>Typical seconds for one demo run, per model (0 = unknown).</summary>");
cs.AppendLine("public static class DemoTimings");
cs.AppendLine("{");
cs.AppendLine("    public static readonly Dictionary<string, int> Seconds = new()");
cs.AppendLine("    {");
foreach (var r in results) cs.AppendLine($"        [\"{r.Id}\"] = {r.Seconds},");
cs.AppendLine("    };");
cs.AppendLine("}");
var csPath = Path.Combine(repoRoot, "FoundryLocalLlmServer.BlazorClient", "DemoTimings.cs");
await File.WriteAllTextAsync(csPath, cs.ToString());
Console.WriteLine($"Wrote {csPath}");

Console.WriteLine($"\nDone: {results.Count} models, {results.Count(r => r.Seconds > 0)} timed, {results.Count(r => r.Seconds == 0)} errored.");
return 0;
